default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: piste_development

test:
  <<: *default
  database: piste_test
  username: shippable
  password: ''

production:
  <<: *default
  database: piste_production
  username: piste
  password: <%= ENV['PISTE_DATABASE_PASSWORD'] %>
